name: Docker-CI

on:
  push:
    branches: [main]
  pull request:
    branches: [main]
  
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pytest
      
    - name: Run test
      run : pytest

  build-publish:
    needs: build-test
    runs-on: ubuntu-latest

      steps:
        - name: Check out
          uses: actions/checkout@v2

        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login-Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
   
        - name: Build and push docker img
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
        
        - name: Image Digest
          run : echo ${{ steps.build-publish.output.digest }}